connectedin/connectedin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('perfis.urls')),
    url(r'^', include('usuarios.urls')),
)

connectedin/perfis/urls.py
from django.conf.urls import patterns, include, url
from perfis import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^perfis/(?P<perfil_id>\d+)$', views.exibir, name='exibir'),
    url(r'^perfis/(?P<perfil_id>\d+)/convidar$', views.convidar, name='convidar'),
    url(r'^perfis/(?P<convite_id>\d+)/aceitar$', views.aceitar, name='aceitar'),
)

'''
url(r'^$', 'perfis.views.index')            <- http://localhost:8000/
url(r'^perfis$', 'perfis.views.exibir')     <- http://localhost:8000/perfis
url(r'^perfis/\d+$', 'perfis.views.exibir') <- http://localhost:8000/perfis/12 (1 ou + digitos)
url(r'^perfis/(?P<perfil_id>\d+)$', 'perfis.views.exibir') <- Espera o perfil_id

OlD - url(r'^perfis/(?P<perfil_id>\d+)$', 'perfis.views.exibir', name='exibir'),
NEW - 
'''

connectedin/usuarios/urls.py
from django.conf.urls import patterns, include, url
from perfis import views
from views import RegistrarUsuarioView

urlpatterns = patterns(
    '',
    url(r'^registrar/$', RegistrarUsuarioView.as_view(), name='registrar'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', {'login_url': '/login/'}, name='logout'),
)

connectedin/perfis/models.py
from django.db import models
from django.contrib.auth.models import User


class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    # email = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('self')  # Auto relacionamento com ele mesmo
    usuario = models.OneToOneField(User, related_name="perfil")

    # Se comporta como se fosse atrinuto
    @property
    def email(self):
        return self.usuario.email

    def convidar(self, perfil_convidado):
        print 'Solicitante -> %s %s' % (self.id, self.nome)
        print 'Convidado   -> %s %s' % (perfil_convidado.id, perfil_convidado.nome)
        convite = Convite(solicitante=self, convidado=perfil_convidado)
        # convite = Convite(solicitante=perfil_convidado, convidado=self)
        convite.save()


class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, related_name='convites_feitos')
    convidado = models.ForeignKey(Perfil, related_name='convites_recebidos')

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)  # Add
        self.solicitante.contatos.add(self.convidado)  # Add
        self.delete()  # Deleta o convite

connectedin/usuarios/models.py
from django.db import models

# Create your models here.

connectedin/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User


class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        user_exists = User.objects.filter(username=self.data['nome']).exists()

        if user_exists:
            self.adiciona_erro('Usuario ja existente')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

connectedin/perfis/views.py
from perfis.models import Perfil, Convite
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

'''
Ao digitar http://localhost:8000/ ele chama essa pagina e retorna o index.html
'''


# Decorator
# @permission_required('perfis.add_convite', raise_exception=True)
@login_required
def index(request):
    return render(request, 'index.html', {'perfis': Perfil.objects.all(), 'perfil_logado': get_perfil_logado(request)})


@login_required
def exibir(request, perfil_id):
    # print 'ID do perfil recebido -> %s ' % (perfil_id)
    # perfil = Perfil()
    perfil = Perfil.objects.get(id=perfil_id)

    perfil_logado = get_perfil_logado(request)
    ja_eh_contato = perfil in perfil_logado.contatos.all()

    # if perfil_id == '1':
    # perfil = Perfil('Gustavo', 'gu@terra.com', '3838-5638', 'Padtec')
    return render(
        request, 'perfil.html',
        {
            "perfil": perfil,
            "ja_eh_contato": ja_eh_contato,
            'perfil_logado': get_perfil_logado(request)
        }
    )


@login_required
def convidar(request, perfil_id):
    perfil_a_convidar = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    perfil_logado.convidar(perfil_a_convidar)
    return redirect('index')


@login_required
def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('index')


@login_required
def get_perfil_logado(request):
    return request.user.perfil
    # return Perfil.objects.get(id=1)

connectedin/usuarios/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic.base import View
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm


# Create your views here.
class RegistrarUsuarioView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)

        if form.is_valid():
            dados_form = form.data

            usuario = User.objects.create_user(
                dados_form['nome'],
                dados_form['email'],
                dados_form['senha']
            )

            perfil = Perfil(
                nome=dados_form['nome'],
                email=dados_form['email'],
                telefone=dados_form['telefone'],
                nome_empresa=dados_form['nome_empresa'],
                usuario=usuario
            )

            perfil.save()

            return redirect('index')

        return render(request, self.template_name, {'form': form})

connectedin/perfis/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>ConnectedINN</title>
    <meta charset="UTF-8">
    <meta charset="viewPort" content="width=device-width">
    <link rel="stylesheet" href="{% static 'styles/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
</head>
<body>
<div class="container">
    <div class="header">
        <ul class="nav nav-pills pull-right">
            <li>
                <a href="{% url 'exibir' perfil_logado.id %}">
                    ID: {{ perfil_logado.id }} - Nome: {{ perfil_logado.nome }}
                </a>
            </li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
        <h3 class="text-muted">
            <a href="{% url 'index' %}">ConnectedINN</a>
        </h3>
    </div>
    <div class="row content">
        {% block body%}
        {% endblock %}
    </div>
</div>
</body>
</html>

connectedin/perfis/templates/index.html
{% extends "base.html" %}

{% block body%}
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Todos os perfis:</strong>
        </div>
        {% if perfis %}
        <ul>
            {% for perfil in perfis %}
            <li>
                <!--
                A tamplate de abaixo é melhor
                <a href="/perfis/{{perfil.id}}">{{perfil.nome}}</a>
                -->
                <!--Coloca o ID no final da URL-->
                <a href="{% url 'exibir' perfil.id %}">{{perfil.nome}}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>Nenhum perfil encontrado</p>
        {% endif %}
    </div>
    <div id="Convites" class="panel panel-default">
        {% with total_de_convites=perfil_logado.convites_recebidos %}
        {% if total_de_convites.count %}
        <div class="panel-heading">
            <strong>
                Você tem {{total_de_convites.count}} convite{{total_de_convites.count| pluralize}} aguardando aprovação
            </strong>
        </div>
        <ul class="list-group">
            {% for convite in total_de_convites.all %}
            <li class="list-group-item">
                {{ convite.solicitante.nome }}
                <a href="{% url 'aceitar' convite.id %}" class="pull-right">Aceitar</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <div class="panel-body">
            <p>Você não possui nenhum convite pendente :(</p>
        </div>
        {% endif %}
        {% endwith %}
    </div>
    <div id="Contatos" class="panel panel-default">
        {% with total_de_contatos=perfil_logado.contatos %}
        {% if total_de_contatos.count %}
        <div class="panel-heading">
            <strong>
                Você tem {{total_de_contatos.count}} contato{{total_de_contatos.count| pluralize}}
            </strong>
        </div>
        <ul class="list-group">
            {% for contato in total_de_contatos.all %}
            <li class="list-group-item">
                <a href="{% url 'exibir' contato.id %}">{{ contato.nome }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <div class="panel-body">
            <p>Você não possui contatos no momento</p>
        </div>
        {% endif %}
        {% endwith %}
    </div>
</div>
{% endblock%}

connectedin/perfis/templates/perfil.html
{% extends "base.html" %}

{% block body %}
<div class="row">
    <div class="col-lg-12">
        <h2 style="margin-top: 0">{{perfil.nome}}</h2>
        <address>
            <strong>{{perfil.nome_empresa}}</strong> <br/>
            <abbr title="Telefone">{{perfil.telefone}}</abbr> <br/>
            <a href="mailto: {{perfil.email}}">{{perfil.email}}</a> <br/>
        </address>
        {% if ja_eh_contato %}
        <div class="well well-sm">Vocês estão conectados!</div>
        {% else %}
        <a href="{% url 'convidar' perfil.id %}">Convidar</a>
        {% endif %}
    </div>
</div>
{% endblock %}

connectedin/usuarios/templates/base_usuario.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt">
<head>
    <title>ConnectedIn</title>
    <meta charset="UTF-8">
    <meta charset="viewPort" content="width=device-width">
    <link rel="stylesheet" href="{% static 'styles/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
</head>

<body>
<div class="container">
    {% block body %}

    {% endblock %}
</div>
</body>
</html>

connectedin/usuarios/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

<form class="form-signin" role="form" action="{% url 'django.contrib.auth.views.login' %}" method="post">
    {% csrf_token %}

    <h2 class="form-signin-heading">Login</h2>
    <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>
    <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>
    <input type="hidden" name="next" value="{{ next }}"/>

    {% if form.errors %}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        Por favor, verifique o Email e/ou Senha informados
    </div>
    {% endif %}

    <a href="{% url 'registrar' %}">registre-se</a>
</form>

{% endblock %}

connectedin/usuarios/templates/registrar.html
{% extends "base_usuario.html" %}

{% block body %}
<form class="form-signin" action="{% url 'registrar' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">
        Crie seu usuário
    </h2>
    <input id="id_email" name="email" type="text" class="form-control" placeholder="Email: " required
           value="{{form.email.value}}">
    <input id="id_nome" name="nome" type="text" class="form-control" placeholder="Nome: " required
           value="{{form.nome.value}}">
    <input id="id_senha" name="senha" type="password" class="form-control" placeholder="Senha: " required
           value="{{form.senha.value}}">
    <input id="id_telefone" name="telefone" type="text" class="form-control" placeholder="Telefone: "
           value="{{form.telefone.value}}">
    <input id="id_nome_empresa" name="nome_empresa" type="text" class="form-control" placeholder="Nome empresa: "
           value="{{form.nome_empresa.value}}"
           required>
    <hr/>
    {% if form.errors %}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <button class="btn btn-lg btn-primary btn-block" type="submit">
        Registrar
    </button>
</form>
{% endblock %}